### ISSUE TITLE
merge fail with uploaded template (file)

### ISSUE THREAD

**Issue by gamegine** [technorabilia/portainer-tools#2]
hello, I came across an error concerning the merge of local templates

step to reproduce 
1 start a new docker with clean configuration
```
# https://www.technorabilia.com/portainer-tools-merge-and-host-app-template-definitions/
version: '3.3'
services:
    portainer-tools:
        container_name: portainer-tools
        environment:
            #- PUID=<puid>
            #- PGID=<pgid>
            - SERVER_URL=localhost
            - PORTAINER_URL=localhost
            #- PORTAINER_USERNAME=<portainer username>
            #- PORTAINER_PASSWORD=<portainer password>
        ports:
            - 9999:9999
        volumes:
            - config:/config
        restart: unless-stopped
        image: technorabilia/portainer-tools
volumes:
  config:
```
2 Upload app template definition file (in this case a.json)
3 select 2 templates and merge
error message was printed
Error in templates/a.json: Invalid URL 'templates/a.json': No schema supplied. Perhaps you meant http://templates/a.json?

it will probably be necessary to add a condition to check if the template is local
app/tools/apptemplates/utils.py
```
    for template in templates:
        template_url = template["url"]
        try:
            response = requests.get(template_url)
            template = json.loads(response.text)
```
